### PR TITLE
REMOVED:  symbolic link

### PR DESCRIPTION
**Pull request by MarQuisKnox**
Removed the symbolic link to the 'syntaxhighlighter_3.0.83', so that the end-user does not have to create this symbolic link on the target server. Now the extension functions properly immediately after installation.

### CODE REVIEW

**Comment by seongjaelee** [comment]
Doesn't the end-user have to create the symbolic link manually anyway, since SyntaxHighlighter.php is referring syntaxhighlighter folder?

**Comment by MarQuisKnox** [comment]
No, creating a symbolic link is not necessary if the directory is named 'syntaxhighlighter' as in this commit. To make it future proof this is the best solution. I've been using your plugin since circa 2012 & I always have to rename the folder to 'synatexhighlighter' on every target system. This commit makes the plugin "just work" without the need for any sysadmin tasks.

**Comment by seongjaelee** [comment]
Didn't see the directory name change. Thanks!

**Comment by MarQuisKnox** [comment]
Great. 
Thanks for merging it!

**Pull request merged**
